---

- name: Build OnMetal Lab Host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Remove current hosts file"
      local_action:
        module: file
        path: ./hosts
        state: absent
      tags:
        - always

    - name: "Create hosts file"
      local_action:
        module: file
        path: ./hosts
        state: touch
      tags:
        - always

    - name: "Add server to hosts file - DFW"
      local_action:
        module: lineinfile
        dest: hosts
        create: yes
        state: present
        line: osic-qa-build-dfw1
      tags:
        - always

    - name: "Add server to hosts file - IAD"
      local_action:
        module: lineinfile
        dest: hosts
        create: yes
        state: present
        line: osic-qa-build-iad1
      tags:
        - iad
